default: &default
  adapter: postgresql

test:
  <<: *default
  url: <%= ENV['DATABASE_URL_TEST'] %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL_DEVELOPMENT'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
